apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1

    deleteDatasources:
      - name: loki
        orgId: 1

    datasources:
    - name: loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
    - name: prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-operator-prometheus:9090

