apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-operator
  namespace: kube-system
spec:
  chart: stable/prometheus-operator
  targetNamespace: monitoring
  valuesContent: |-
    alertmanager:
      enabled: false

    grafana:
      enabled: true
      image:
        tag: master
      env:
        GF_EXPLORE_ENABLED: true
      adminUser: admin
      adminPassword: R_M_S4evR

    prometheusOperator:
      createCustomResource: false

    prometheus:
      prometheusSpec:
        retention: 2w
        serviceMonitorSelector:
          selector:
            matchLabels:
              service: monitor
