---
- hosts: master[0]
  remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - { role: k3s/deploy, apps: [ 'rook-operator.yml' ], tags: [ 'rook' ] }
    - { role: k3s/deploy, apps: [ 'ceph-cluster.yml' ], tags: [ 'ceph' ] }

